import Head from 'next/head'
import styled from 'styled-components'
import { gsap } from 'gsap'
import { useRef, useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.scss'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faAngleRight } from '@fortawesome/free-solid-svg-icons'

export default function Home() {
  const [scrollPos, setScrollPos] = useState(0)
  const header = useRef()
  const flowersSvg = useRef()
  const subHeader = useRef()
  const indexSidePage = useRef()
  let instaImage = useRef([])

  const handleScroll = () => {
    const position = window.pageXOffset
    console.log(position)
    setScrollPos(position)
  }

  const IndexBg = styled.div`
    position: fixed;
    z-index: 0;
    height: 100vh;
    width: 100vw;
    background-image: linear-gradient(
      ${scrollPos / 8}deg,
      rgb(231, 113, 125),
      rgb(232, 160, 112),
      rgb(232, 218, 113)
    );
  `

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true })
  })

  useEffect(() => {
    gsap.from(header.current, {
      marginLeft: -300,
      opacity: 0,
      duration: 2
    })

    gsap.from(subHeader.current, {
      marginLeft: 300,
      opacity: 0,
      duration: 2
    })

    gsap.fromTo(
      flowersSvg.current,
      {
        bottom: '100%'
      },
      {
        bottom: 0,
        duration: 2,
        delay: 1.5,
        ease: 'bounce'
      }
    )
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Harvest Moon Dahlias</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.indexWideWrapper}>
        <Navbar color='rgba(255, 255, 255, 1)' />
        <IndexBg />
        <div className={styles.indexPageWrapper}>
          <img
            className={styles.indexFlowersSvg}
            src='/images/farm-girl.svg'
            ref={flowersSvg}
          />
          <div className={styles.indexContentWrapper}>
            <h1 className={styles.indexHeader} ref={header}>
              Dahlias are all we do!
            </h1>
            <h2 className={styles.indexSubheader} ref={subHeader}>
              Harvest Moon is a family owned, local Dahlia nursery in Howell,
              NJ.
            </h2>
          </div>
          <div className={styles.scrollRightButtonWrapper}>
            <div className={styles.scrollRightButtonText}>what we do</div>
            <FontAwesomeIcon
              className={styles.scrollRightButton}
              icon={faAngleRight}
              onClick={() =>
                indexSidePage.current.scrollIntoView({ behavior: 'smooth' })
              }
            />
          </div>
        </div>
        <div className={styles.indexSidePage} id='aboutus' ref={indexSidePage}>
          <div className={styles.indexSidePageWrapper}>
            <h2 className={styles.indexSidePageHeader}>What we do</h2>
          </div>
          <h1 className={styles.indexSidePageFooter}>harvest moon dahlias</h1>
        </div>
      </div>
    </div>
  )
}
